name: keu_pemasukan
description: "H1D022006"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - gif/

  fonts:
    - family: Verdana
      fonts:
        - asset: fonts/verdana.ttf
        - asset: fonts/verdana-bold.ttf
          weight: 700
        - asset: fonts/verdana-bold-italic.ttf
          weight: 700
          style: italic